### ISSUE TITLE
Unable to display amount of healing/shields you did to target

### ISSUE THREAD

**Issue by Reiyhn** [Stanzilla/AdvancedInterfaceOptions#17]
Hi,

For some reason i'm unable to show the amount of healing/shields I did to target - when i tick the options and hit ok they have been automatically un-ticked when i get back into the options menu.

Very frustrating, unsure how to fix this.

Cheers

**Comment by Restomagus** [comment]
I am having the SAME issue1

**Comment by Stanzilla** [comment]
Classic or Retail?

**Comment by Reiyhn** [comment]
Classic.

**Comment by Stanzilla** [comment]
Yeah Blizzard remove those in Classic
