### ISSUE TITLE
Floating Combat Text issue

### ISSUE THREAD

**Issue by Restomagus** [Stanzilla/AdvancedInterfaceOptions#18]
I do not know if this is because of running other addons or not

I go into AdvancedInterfaceOptions addon, I go into Floating Combat Text, I select Healing, I click "Okay," then healing numbers don't show. I go back to check, it has unchecked itself.

The healing option does not stick?

**Comment by Ketho** [comment]
Yeah CVar floatingCombatTextCombatHealing was removed in classic
(we forgot or were too lazy/busy to remove that option)

**Comment by DamirHalilovic** [comment]
> Yeah CVar floatingCombatTextCombatHealing was removed in classic
> (we forgot or were too lazy/busy to remove that option)

But it wasn't. If I type in /console floatingCombatTextCombatHealing 1 it works fine.
