### ISSUE TITLE
(classic) SharedUIPanelTemplates.lua:864: attempt to index field 'PortraitFrame' (a nil value)

### ISSUE THREAD

**Issue by R-Adrian** [Stanzilla/AdvancedInterfaceOptions#20]
in WoW classic, i decided to tweak some CVARs via AIO and i think i managed to mess some of them that are not supposed to be touched... i'm now getting this LUA error on reload:
(note; AIO is the only enabled addon at this point of my testing)

```
Message: Interface\SharedXML\SharedUIPanelTemplates.lua:864: attempt to index field 'PortraitFrame' (a nil value)
Time: Sun Sep  1 11:48:25 2019
Count: 1
Stack: Interface\SharedXML\SharedUIPanelTemplates.lua:864: attempt to index field 'PortraitFrame' (a nil value)
Interface\SharedXML\SharedUIPanelTemplates.lua:864: in function `OnLoad'
Interface\FrameXML\CharacterFrame.lua:63: in function <Interface\FrameXML\CharacterFrame.lua:62>

Locals: self = CharacterFrame {
 0 = <userdata>
}
use2XFrameTextures = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'PortraitFrame' (a nil value)"
```

**note: this error seems to be caused by the CVAR `useHighResolutionUITextures` being set to 1, because classic WoW has no support for high resolution textures.**

**Comment by Ketho** [comment]
Yeah it's a blizzard bug, they removed the textures but just forgot about that cvar probably

**Comment by semlar** [comment]
Cleaning up old issues; reopen if this is something that should be addressed.
