### ISSUE TITLE
"Floating Combat Text on Me" ONLY "Leave/Enter Combat"

### ISSUE THREAD

**Issue by Vaits** [Stanzilla/AdvancedInterfaceOptions#21]
Thanks for the Addon! is it possible to turn on "Floating Combat Text on Me" to show ONLY "Enter/Leave Combat"? When "Floating Combat Text on Me" is turned on, it always includes healing and damage received. I tried to use the CVar Browser to edit this, but I couldn't find options for that. Help and infos are appreciated! I'm using the Addon for retail WoW. 
(wasn't able to ask this on curseforge - parserror)

**Comment by Ketho** [comment]
To disable healing and damage received you'd have to use this script with https://addon.bool.no/ or [REHack](https://www.curseforge.com/wow/addons/rehack)

```lua
local events = {
	"HEAL",
	"HEAL_CRIT",
	"PERIODIC_HEAL",
	"PERIODIC_HEAL_CRIT",
	"DAMAGE",
	"DAMAGE_CRIT",
	"SPELL_DAMAGE",
	"SPELL_DAMAGE_CRIT",
}

local function OnEvent(self, event, addon)
	if addon == "Blizzard_CombatText" then
		for _, v in pairs(events) do
			COMBAT_TEXT_TYPE_INFO[v].show = false
		end
	end
end

local f = CreateFrame("Frame")
f:RegisterEvent("ADDON_LOADED")
f:SetScript("OnEvent", OnEvent)

```

**Comment by Vaits** [comment]
It works like a charm! Thank you very much for the fast and helpful coding!
