### ISSUE TITLE
Minimap button appearing when turned off

### ISSUE THREAD

**Issue by Sipollo** [Stanzilla/AdvancedInterfaceOptions#25]
The minimap button is disabled in my options, but it is appearing when I log in.

Toggling the button & back off again will cause it to disapper, but only for the rest of that session.

Login again and its back!

**Comment by Stanzilla** [comment]
I'm sorry but we don't even have a minimap button?

**Comment by Sipollo** [comment]
Urgh; I'm sorry... completely confused with reality here :(
