### ISSUE TITLE
absorb bub

### ISSUE THREAD

**Issue by Vaits** [Stanzilla/AdvancedInterfaceOptions#26]
I love your FloatingCombatTextOnly-Script, but the script still shows absorb effects like you can see in the clip below. Is it possible to fix this?

original script:
https://github.com/Stanzilla/AdvancedInterfaceOptions/issues/21

absorb bug (when the dk is attack me):
https://www.twitch.tv/videos/490060101

*spelling error in the title...

**Comment by Ketho** [comment]
> absorb bug (when the dk is attack me):

You should be able to toggle it in the `interface options -> Shields (Self)`
https://streamable.com/zn1q4

Otherwise you can use this command
```
/console floatingCombatTextCombatHealingAbsorbSelf 0
```

In the future you can also ask on the [wowuidev](https://discord.gg/sVQCHr5) discord
