### ISSUE TITLE
Disables Load out of date AddOns.

### ISSUE THREAD

**Issue by InkDevil666** [Stanzilla/AdvancedInterfaceOptions#27]
When i have AdvancedInterfaceOptions enabled it keeps disabling the Load out of date AddOns option. It also makes tips for new players keep popping up efter every login/reload. Example: Opening the world map will display: "Complete world quests for this faction to receive a bonus reward", Opening the inventory it pops up with "Click this button to lean up your bags. It auto-sorts and moves items out of the way to make room for new items". Tried deleting the addon completely, resetting all settings, no addons except AIO.

**Comment by Ketho** [comment]
Can't reproduce in retail with v1.3.3

**Comment by semlar** [comment]
An extremely outdated version of AIO might be capable of doing this when "enforce cvar settings" is enabled, but it should not be happening with the current addon.

Verify that you are running the latest version (1.3.3) of the addon and see if it still happens.

**Comment by InkDevil666** [comment]
Clearing the old settings seem to have done the trick. Everything works as normally again.
