### ISSUE TITLE
Display Lua errors won't stay checked

### ISSUE THREAD

**Issue by Sailorarctic** [Stanzilla/AdvancedInterfaceOptions#28]
I click the checkbox to turn off the lua errors and as soon as I phase in or out of somewhere the settings are set back to the default of showing them, I have the checkbox the says "enforce settings on startup" checked as well but the lua errors keep coming back on. Retail version

**Comment by jamesw71** [comment]
I am having the same issues...started getting a ton of LUA errors when 9.1.5 came out, most seem centered around ElvUI which I check on updates at least once a week....but sick and tired of the LUA errors on my screen.  I have "enforce settings on startup" checked and the checkbox to turn off the lua errors keeps getting turned off when I log off and back on.  Same if I change characters it will go unchecked again anytime I log to my character select screen.

**Comment by jamesw71** [comment]
I even went so far as to delete my WTF and Interface folders etc like Blizzard troubleshooting suggest to do first, I reinstalled all of my addons from scratch, including AIO and still get huge amounts of LUA errors and AIO will not keep the checkbox marked for turning off LUA errors.

**Comment by Ketho** [comment]
@jamesw71 Does this still happen with all other addons disabled?
What does the cvar browser show for which addon last modified it?

![image](https://user-images.githubusercontent.com/1073877/142759765-19f4ac87-8940-4cd3-a49b-7bf303981e45.png)

**Comment by jamesw71** [comment]
ok seems to be a workaround if I turn off all other addons (or maybe recent fix to another addon did it, not sure) set AIO to the options I want and then turn all the other addons back on.  

For couple months now the LUA errors kept popping up and seems everytime I played a new character I kept having to mess with getting it fixed.

I tried that today, the character I played yesterday was getting errors all day and the Display LUA Errors would not stay unchecked.  Today, after updating addons and ElvUI I wasn't getting the errors anymore and the box stayed unchecked.

I logged to another character I hadn't played in awhile and it went back to displaying errors again and the box would keep rechecking itself after relogging so I disabled all addons except for AIO, set my settings for AIO and then reloaded the UI and it finally kept my settings.  I turned the addons back on and AIO kept the settings, it seems I am only having issue with AIO if attempt to update it's settings with my other addons enabled.

Thankyou.  At least it works for now.

**Comment by jamesw71** [comment]
![image](https://user-images.githubusercontent.com/73526015/142760954-660e642f-91b8-4afd-9970-542257a24dba.png)

**Comment by jamesw71** [comment]
ok I logged back to my original character with addons still enabled, and the error button is checked again, not sure what is rechecking it so posted picture...how else do I figure out what is turning it back on?

**Comment by Ketho** [comment]
I have no idea, sorry. That screenshot does not identify which addon possibly changed that cvar last.

**Comment by jamesw71** [comment]
I know, what is even odder, as I'm going thru some of my alts doing mount farming some have the option checked and are getting errors, some do not so I can't pinpoint what is causing the addon to check and uncheck the option on its own.

**Comment by semlar** [comment]
I just pushed an update that should improve AIO's ability to track whatever is modifying this CVar.

Try installing version 1.7.0, disable Lua errors, then /reload the ui and use the CVar Browser again to check if 'scriptErrors' has any more useful information in its tooltip.

Your addons should not be throwing errors and ignoring them can drastically impact your game's performance. It's best to update or disable problematic addons, but you can use [BugSack](https://www.curseforge.com/wow/addons/bugsack) to permanently hide these errors if necessary.

**Comment by jamesw71** [comment]
Well, not sure what is going on, no errors today, AIO seems to be holding with the update and the error tracking is staying off.

I run a dozen or so addons that are seemingly never updated and don't have replacements, don't have any issues playing other than these occasional issues stopping reporting.  I also run different profiles depending on if I'm questing, raiding or leveling so not all addons are running all the time.
