### ISSUE TITLE
TimerAugment Error

### ISSUE THREAD

**Issue by mcd8604** [Stanzilla/AdvancedInterfaceOptions#29]
Date: 2020-01-17 13:52:37
ID: 265
Error occured in: Global
Count: 1
Message: ..\SharedXML\C_TimerAugment.lua line 24:
   C_Timer.After duration is too large
Debug:
   [C]: After()
   ..\SharedXML\C_TimerAugment.lua:24:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:
(*temporary) = 900
(*temporary) = <function> defined @Interface\SharedXML\C_TimerAugment.lua:14

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.46.04.11303.01
  AtlasClassicWoW, vv1.45.01.11303.05
  AtlasLootClassic, vv1.4.4
  AtlasLootClassicData, vv1.4.4
  AtlasLootClassicDungeonsAndRaids, vv1.4.4
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BattlegroundTargets, v11303-4
  CharacterStatsClassic, v3.1
  ClassicAuraDurations, v
  ClassicCastbars, vv1.2.2
  ClassicCastbarsOptions, v
  CTBarMod, v8.2.5.5
  CTBottomBar, v8.2.5.7
  CTBuffMod, v8.2.5.5
  CTCore, v8.2.5.6
  CTExpenseHistory, v8.2.5.6
  CTLibrary, v8.2.5.7
  DBMCore, v1.13.30
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  GatherMate2, v1.45.5
  GuildRosterManager, v1.831
  HonorAssist, v0.9.2
  HonorTracker, vv3.2.5
  HPH, v2.9
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixMaps, v1.13.44
  LeatrixPlus, v1.13.45
  NugEnergy, v1.13.12
  OmniBar, vv10.7
  OmniCC, v8.3.1
  OPie, vAncient Walnut 6
  Quartz, v3.5-classic-5
  Questie, v5.5.1
  SheepMonitor, v1.22
  Spy, v1.0.21
  SSPVP, v
  Stubby, v8.2.6376 (SwimmingSeadragon)
  WeakAuras, v2.16.0
  ZPerl, v5.8.9
  ZPerlArcaneBar, v
  ZPerlCustomHighlight, v
  ZPerlOptions, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=721)

**Comment by semlar** [comment]
This is not being caused by this addon.

I believe this error is related to your system uptime being too large for the game's timer system to handle.

Restarting your computer should fix it!
