### ISSUE TITLE
Save/Load CVar manually?

### ISSUE THREAD

**Issue by Xruptor** [Stanzilla/AdvancedInterfaceOptions#32]
Is there an option  where you can press a button and save all the currently modified CVar (including the character ones) into a DB?  That way you have on file every single (red modified) value that has been adjusted in the CVar browser.  Then I can press a button and load it manually instead of it being enforced everytime I login?  I'm an addon developer and sometimes I need to test modifications to the Cvar.  Having the option to save all my CVar preferences and then manually load them when I'm done would be nice.

I currently notice that in the DB it doesn't seem to save EVERY modified Cvar value.  My CustomVars and CharVars are empty table but the ModifiedCVars only have a fraction of what has been modified in the CVar Browser.

Thanks in advance!

**Comment by Katzenhirn** [comment]
Same question! I would be lovely to save / export and import all cvars at once. Especally when you try new addons that  changes some cvars you didn't catch at all.

**Comment by Xruptor** [comment]
Nevermind!

Since apparently this was so difficult to add to this particular addon, I went ahead and made a simple addon to save/restore CVars settings.

[](https://www.curseforge.com/wow/addons/cvarsbackup)
[](https://www.wowinterface.com/downloads/info25942-CVarsBackup.html)

**Comment by Katzenhirn** [comment]
> Nevermind!
> 
> Since apparently this was so difficult to add to this particular addon, I went ahead and made a simple addon to save/restore CVars settings.
> 
> https://www.curseforge.com/wow/addons/cvarsbackup
> https://www.wowinterface.com/downloads/info25942-CVarsBackup.html

<3

**Comment by Stanzilla** [comment]
Why did you not make a Pull Request instead?

**Comment by Xruptor** [comment]
> Why did you not make a Pull Request instead?

Good question! 😄  I typically do not do Pull Requests unless an author agrees to it, or at least requests additional code assistance.  I've had incidents in the past where I've done pull requests and they just sit there and are never accepted. (Sometimes just outright rejected 😞).  So as a habit, I file a issue ticket first and check whether an author responds or not.  Sometimes they do and sometimes they don't.  It varies as I know what it is to be overwhelmed with addon modifications or cleanup.

I had posted this on Mar 6, 2020 and the ticket has been opened since that time.  I hadn't received a single response, until now.  I figured the author was just not available or interested in adding the code.  So I decided just to make a very tiny addon to do the backup/restore of CVars myself.  I mean, it has been quite a long time since this request was put in.  I would have been more than glad to do a pull request if I had gotten a response.

Anyways thanks for taking the time to respond!  Thanks for a wonderful addon btw!

**Comment by Stanzilla** [comment]
Alright, no problem. I would love to defer to @semlar for the topic of cvar loading and saving, we did have a feature like that (sort of) but it was causing a few problems when other addons changed them etc, so I manual option might be better but not sure.

**Comment by semlar** [comment]
Implemented by d232e3ab1343803c2eac4515029a4c1141ad8b95
