### ISSUE TITLE
showQuestTrackingTooltips unable to assign value in cvar browser

### ISSUE THREAD

**Issue by Inexa5** [Stanzilla/AdvancedInterfaceOptions#39]
Hello, unable to assign desired value to showQuestTrackingTooltips in cvar browser or by using /run SetCVar(''showQuestTrackingTooltips'', 0). 

- This has been observed since Shadowlands pre-patch. 
- All other addons are disabled. 
- The browser doesn't indicate that any other addon has modified it. 
- The browser also doesn't show current value, but tooltips are showing tracked quest objectives (value 1).

Thank you!

**Comment by Ketho** [comment]
It looks like CVar showQuestTrackingTooltips was removed in patch 9.0.2, I assume the functionality now defaults to on without being able to disable it
https://wow.gamepedia.com/Patch_9.0.2/API_changes

**Comment by Inexa5** [comment]
Ok, thanks!
