### ISSUE TITLE
button glow/flash

### ISSUE THREAD

**Issue by mspykerez** [Stanzilla/AdvancedInterfaceOptions#40]
Any change to implement an option to disable blizzard button glow on the auction bars ? (for like when a spell procs something and flashes the border of the icon on the auction bars - I want to disabled that!).

**Comment by Ketho** [comment]
I don't think there's a cvar for that. This quick and dirty snippet seems to remove it though, you can turn it into an addon with https://addon.bool.no/
```lua
ActionButton_ShowOverlayGlow = function() end
```
