### ISSUE TITLE
Feature Request: Pet Nameplate Cvar

### ISSUE THREAD

**Issue by Moki182** [Stanzilla/AdvancedInterfaceOptions#49]
Hi

Could you add a line to the Cvar Browse option to set the Size of the Enemy Pet Nameplates?
(so it can be smaller)

![image](https://user-images.githubusercontent.com/84582380/161383874-807a4bac-bc67-4e77-83a6-2b1fe170b98a.png)

**Comment by Stanzilla** [comment]
That's not possible, we can only list the options that Blizzard supports

**Comment by Moki182** [comment]
Ahh nevermind
Someone else made it possible for me.

![image](https://user-images.githubusercontent.com/84582380/161449035-e23bcd70-3372-4327-96c3-b1a6c4e848b4.png)
