### ISSUE TITLE
Changing nameplate overlap

### ISSUE THREAD

**Issue by rakkarage** [Stanzilla/AdvancedInterfaceOptions#50]
I cannot seem to change the nameplate overlap with this installed?
/run C_CVar.SetCVar("nameplateOverlapH", .777)
/run C_CVar.SetCVar("nameplateOverlapV", .333)
If I change it from the cvar browser or macro it looks fine until /reload? then it goes back to default (no "changed by" message)
So i disabled all addons and set it in the Config.wtf and works fine till i turn on advanced interface options and it gets reset to default again...
[![Wo-WScrn-Shot-041622-143705.jpg](https://i.postimg.cc/kgcxQLNF/Wo-WScrn-Shot-041622-143705.jpg)](https://postimg.cc/k22691pB)
Says was changed by ChatFrame? idk
Please & Thanks!

**Comment by Stanzilla** [comment]
Do you have "Enforce Settings on Startup" enabled?

**Comment by rakkarage** [comment]
Aha. Thanks. Sorry.
