### ISSUE TITLE
Wrath Classic Support / TOC Update

### ISSUE THREAD

**Issue by boktai1000** [Stanzilla/AdvancedInterfaceOptions#53]
Could we get a TOC update / version published for Wrath Classic? Even if it's currently supported, it would be nice to not have updaters and game complaining about out of date addons.

Thank you!

**Comment by Stanzilla** [comment]
That was already done a while ago, see alpha versions

**Comment by boktai1000** [comment]
Ah. I didn't see the published Alphas on Curseforge since they don't show by default unless you click View All on the website. Alright, looking forward to it!
