### ISSUE TITLE
[WotLK] Game Completely Freezes with CVAR List Open

### ISSUE THREAD

**Issue by stratoru** [Stanzilla/AdvancedInterfaceOptions#54]
Hey Stanzilla!

This is an issue I've been trying to debug myself for quite some time but have been unable to do so. Any assistance would be appreciated.

The issue is basically as the title says. Once opening the AIO CVAR browser/list (the menu that pops up when you type /cvar), the game will either entirely freeze, only getting better if you mash ESC for several seconds to make the AIO menu disappear, or sometimes the game will freeze so badly the game will completely crash without any error report. Other times, the game will freeze to a lesser extent, with about 1 frame showing per 5 seconds. No rhyme or reason to the severity. 

This is using the most recent version of AIO, however this has been an issue going back at least 1 year. It is character specific, occurring on 1 of my toons, but not on the other 2. 

To make things more confusing, following a realm transfer of all 3 toons, the toons affected SWITCHED. As in, the two unaffected toons are now affected. The affected toon is now unaffected. I have attempted to restore default settings of AIO, tried running AIO without any other addons, etc., to no avail. No errors are thrown for BugSack ever. 

Any ideas? I have not seen this error reported before. It must be an infinite loop of some sort that isn't being caught by BugSack.

**Comment by semlar** [comment]
Does this happen with no other addons loaded?
