### ISSUE TITLE
Unable to set loot to leftmost bag or reverse clean up

### ISSUE THREAD

**Issue by Zifijo** [Stanzilla/AdvancedInterfaceOptions#57]
Title says it all. Option is missing and unsure how to enable this on new toons

**Comment by Duranna144** [comment]
Same issue. Addon version 10.0.0 and patch 10.0.2.46658

**Comment by Duranna144** [comment]
I discovered today the script was changed, but it is still in the game.
For looting to leftmost bag: /run C_Container.SetInsertItemsLeftToRight(true) 

For reverse sorting: /run C_Container.SetSortBagsRightToLeft(true)

I assume that was updated in the most recent update, but just wanted to let you know in case it had not been :)
