### ISSUE TITLE
Hints and bags

### ISSUE THREAD

**Issue by Dohtur-Frag** [Stanzilla/AdvancedInterfaceOptions#59]
Hints not show. Some hints show (for drop boxes), but MOSTLY (for check boxes) no.
"Loot To Leftmost Bag" do nothing.
---
Update.
"Loot To Leftmost Bag" work well if "Reverse Clean Up Bags" not selected.
Mostly problems with Blizz's logic. :(

**Comment by Stanzilla** [comment]
Yeah that is on them
