### ISSUE TITLE
Various Errors After Ulduar Patch (WotLK Version)

### ISSUE THREAD

**Issue by pedrorafaelpadilla** [Stanzilla/AdvancedInterfaceOptions#64]
Error 1:
Interface_Wrath\FrameXML\Bindings.xml:1 Interface/AddOns/AdvancedInterfaceOptions/browser.lua:1 (null)

Error 2:
Interface/AddOns/AdvancedInterfaceOptions/browser.lua:1 (null)

Error 3:
Frame:CreateTexture(): Couldn't find inherited node "1"
[string "=[C]"]: in function `CreateTexture'
[string "@Interface/AddOns/AdvancedInterfaceOptions/semlib/widgets.lua"]:225: in function `CreateListFrame'
[string "@Interface/AddOns/AdvancedInterfaceOptions/browser.lua"]:153: in main chunk

Locals:
(*temporary) = "Frame:CreateTexture(): Couldn't find inherited node "1""

**Comment by Stanzilla** [comment]
I cannot repro this atm
