### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Rustcole** [Stanzilla/AdvancedInterfaceOptions#65]
Hello, I am sure this is some setting that I have selected that the game doesn't like, but I can't figure out which and I am getting this Lua error, any help/advice would be much appreciated, love the addon!

1x [ADDON_ACTION_BLOCKED] AddOn 'AdvancedInterfaceOptions' tried to call the protected function 'CompactRaidFrame18:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Wrath/FrameXML/CompactUnitFrame.lua"]:164: in function <Interface_Wrath/FrameXML/CompactUnitFrame.lua:154>
[string "=[C]"]: in function `CompactUnitFrame_SetUnit'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:318: in function `CompactRaidFrameContainer_AddUnitFrame'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:277: in function `CompactRaidFrameContainer_AddPets'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:182: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:62: in function `CompactRaidFrameContainer_OnEvent'
[string "*Blizzard_CompactRaidFrameContainer.xml:79_OnEvent"]:1: in function <[string "*Blizzard_CompactRaidFrameContainer.xml:79_..."]:1>

**Comment by Stanzilla** [comment]
That's a Blizzard error

**Comment by Rustcole** [comment]
ok thank you!
