### ISSUE TITLE
Addon doesnt load on 1.15 Classic ERA

### ISSUE THREAD

**Issue by PeTeFIN** [Stanzilla/AdvancedInterfaceOptions#73]
The addon doesnt load at all. You cannot access it via addon options or the /aio command. This is ofc with "load all old addons" enabled.

**Comment by jimmble** [comment]
The error is:
`...ace/AddOns/AdvancedInterfaceOptions/basicOptions.lua:272: attempt to call global 'GetCVarInfo' (a nil value)
[string "@Interface/AddOns/AdvancedInterfaceOptions/basicOptions.lua"]:272: in function ``newSlider'
[string "@Interface/AddOns/AdvancedInterfaceOptions/basicOptions.lua"]:444: in main chunk`

**Comment by semlar** [comment]
Blizzard has renamed `GetCVarInfo` to `C_CVar.GetCVarInfo`

Fixed by 1bd0d61
