### ISSUE TITLE
Feature Request - Edit Cvars directly from CVar Browser

### ISSUE THREAD

**Issue by boktai1000** [Stanzilla/AdvancedInterfaceOptions#77]
I think it would be great to be able to adjust and maybe reset values back to default from the CVar Browser itself. I know I can search and lookup the command manually, but I think the whole point of the CVar Browser would be to avoid having to look all that up and do things directly from the game itself

Unless I'm mistaking something with functionality - please let me know! Thanks for your consideration :) 

![image](https://github.com/Stanzilla/AdvancedInterfaceOptions/assets/9054563/0cde8b2b-21de-4bb6-94b9-54c2c900b525)

**Comment by Stanzilla** [comment]
You can click on the value to edit it
