### ISSUE TITLE
Some cvars keep resetting to default after 10.2.7 patch

### ISSUE THREAD

**Issue by biterbol** [Stanzilla/AdvancedInterfaceOptions#80]
"NameplateOverlapH" and "NameplateOverlapV" cvars are resetting to default everytime i login. 
I tried disabling every addon except aio but its still resetting. 
Enforce Settings on Startup is enabled. I have tried backup settings and restore settings multiple times but it doesn't seem to work. 
![Screenshot_1](https://github.com/Stanzilla/AdvancedInterfaceOptions/assets/169729705/bd845da7-54b8-4025-9f6d-1cbfab207f37)

**Comment by romracer** [comment]
Hi,

I was noticing CVars resetting on SoD too.  The addon will remove a CVar from its list if it finds another addon modifies it, except the built-in Blizzard tool.  Except the pattern matching for the built-in CvarUtil no longer matches some of the filenames in the various WoW clients.

Try the fix in the linked PR (#81) and see if it helps.  It has fixed the issue on SoD for me.
