### ISSUE TITLE
The War Within Beta

### ISSUE THREAD

**Issue by xenophanesnsb** [Stanzilla/AdvancedInterfaceOptions#82]
I know it's obviously very early in The War Within Beta, but since your addon is so integral to my experience (one of which is the ability to enable the Steelseries World of Warcraft MMO Mouse to work), I'd love to hear that you may be working on a working update to test soon.

Thanks as always for your hard work on this addon.

Xeno

**Comment by Stanzilla** [comment]
should work with the latest alpha
