### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by Eviloverlord1989** [Stanzilla/AdvancedInterfaceOptions#94]
Happens often during the prepatch event routine of combat and flying off, blocks off all keybinds except the 1 button.
Stops happening when I turn off AIO and leave the rest on.

5x [ADDON_ACTION_FORBIDDEN] AddOn 'AdvancedInterfaceOptions' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseAction'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:342: in function `handler'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:667: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:649>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:681: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:674>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:723: in function `SecureActionButton_OnClick'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:100: in function `TryUseActionButton'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:135: in function `ActionButtonDown'
[string "ACTIONBUTTON2"]:2: in function <[string "ACTIONBUTTON2"]:1>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by Stanzilla** [comment]
Not a AIO bug
