### ISSUE TITLE
Any chance we can add the Reduced Camera Collision cvars?

### ISSUE THREAD

**Issue by brittyazel** [Stanzilla/AdvancedInterfaceOptions#95]
As outlined here:
https://www.wowhead.com/news/increase-visibility-with-silhouette-and-camera-collision-options-in-the-war-345671

Any chance we can have these added? It seems like it would be best presented as two options, one that turns the feature on/off, and a slider that activates when turned on and allows you to slide from 0->10.

I'm happy to add it in myself if you think it would be a worthwhile addition.

**Comment by Stanzilla** [comment]
yup, I'd take it!

**Comment by brittyazel** [comment]
I just put the PR in!
